name: BackTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
        path: "./backend"

    - name: Verify dependencies
      working-directory: ./backend
      run: go mod verify

    - name: Build the project
      working-directory: ./backend
      run: go build

    - name: Run go vet
      working-directory: ./backend
      run: go vet

    - name: Install staticcheck
      working-directory: ./backend
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      working-directory: ./backend
      run: staticcheck

    - name: Install golint
      working-directory: ./backend
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      working-directory: ./backend
      run: golint

    - name: Run tests
      working-directory: ./backend
      run: go test -race -vet=off
